### ISSUE TITLE
Twente Milieu (2goMobile?) stopped supporting x-www-form-urlencoded

### ISSUE THREAD

**Issue by robje** [ToonSoftwareCollective/wastecollection#1]
according to [frenck / python-twentemilieu | issue 57](https://github.com/frenck/python-twentemilieu/issues/57) Twente Milieu stopped supporting x-www-form-urlencoded.

I'm not a Qt /QML expert, but looking at WastecollectionApp.qml lines 653 and 711 it seems x-www-form-urlencode is uses.

The posted resolution in frenk-issue 57 is to change posting json-data. Please implement this also for wastecollection.

**Comment by ToonzDev** [comment]
ik ga ernaar kijken. Lijkt niet zo'n groot probleem

**Comment by ToonzDev** [comment]
still working as expected
