### ISSUE TITLE
No data for Drimmelen

### ISSUE THREAD

**Issue by bafplus** [ToonSoftwareCollective/wastecollection#9]
After selecting the settings for Drimmelen (19) with zip 4844VP it won't pull data and the list stays white. Is Drimmelen still working correctly?

**Comment by ToonzDev** [comment]
Drimmelen chnaged their website. I implemented a workaround in version 4.65 (will be published shortly in the ToonStore).
You will have to manually download the calendar from drimmelen.nl and copy to file to toon as /root/waste/waste_calendar.ics
Download needs to be repeated every time a new calendar is published (typically once a year)
